- name: install docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker.io
    - docker-compose
    update_cache: yes
  become: yes
- name: add ubuntu to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  become: yes
